---
apiVersion: dataflow.argoproj.io/v1alpha1
kind: Pipeline
metadata:
  annotations:
    dataflow.argoproj.io/description: Amazing kickerscore attempt
    dataflow.argoproj.io/owner: argoproj-labs
  name: kickerscore-pipeline
spec:
  steps:
    # Step 1:
    # Implement something that makes sure that only valid teams pass, that means to exclude invalid and cheaters.

    # Step 2:
    # Implement a mapping to only extract the winner data from the json messages.

    # Step 3:
    # Using that information, you can create additional steps.
